/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // 为动态类名添加白名单
    {
      pattern: /^(bg|text|border)-(primary|secondary|accent|destructive|muted|foreground|background|card|popover)$/,
    },
    {
      pattern: /^(bg|text)-(primary|secondary|accent|destructive|muted|foreground)-foreground$/,
    },
    {
      pattern: /^(bg)-(primary|secondary|accent|destructive|muted)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    {
      pattern: /^(text)-(primary|secondary|accent|destructive|muted)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    {
      pattern: /^(border)-(primary|secondary|accent|destructive|muted)-(50|100|200|300|400|500|600|700|800|900)$/,
    },
    // 动画类
    'animate-fade-in',
    'animate-slide-up',
    'animate-scale-in',
    'animate-float',
    'animate-pulse-slow',
    // 响应式类
    'sm:text-5xl',
    'lg:text-6xl',
    'sm:text-2xl',
    'sm:flex-row',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'lg:grid-cols-4',
    'container',
    'mx-auto',
    'px-4',
    'px-6',
    'px-8',
    'max-w-2xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'gap-4',
    'gap-6',
    'gap-8',
    // 布局类
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'flex',
    'flex-col',
    'flex-wrap',
    'items-center',
    'justify-center',
    'justify-between',
    'space-y-4',
    'space-y-8',
    // 悬停效果
    'hover:shadow-lg',
    'hover:shadow-xl',
    'hover:-translate-y-1',
    'hover:bg-accent',
    'hover:text-accent-foreground',
    // 背景渐变
    'bg-gradient-to-br',
    'from-blue-50',
    'via-white',
    'to-purple-50',
    'bg-gradient-to-r',
    'from-primary',
    'to-purple-600',
    // 透明度和模糊
    'bg-white/80',
    'backdrop-blur-md',
    'border-white/20',
    'supports-[backdrop-filter]:bg-background/60',
    // 其他常用类
    'relative',
    'overflow-hidden',
    'absolute',
    'inset-0',
    'text-center',
    'text-left',
    'text-right',
    'text-4xl',
    'text-3xl',
    'text-xl',
    'text-lg',
    'text-sm',
    'text-xs',
    'font-bold',
    'font-semibold',
    'font-medium',
    'block',
    'inline-block',
    'inline-flex',
    'whitespace-nowrap',
    'rounded-md',
    'rounded-lg',
    'rounded-full',
    'rounded-sm',
    'p-6',
    'p-4',
    'p-8',
    'pt-8',
    'pb-6',
    'mb-4',
    'mb-6',
    'mb-16',
    'mt-16',
    'mt-20',
    'h-10',
    'h-11',
    'h-12',
    'w-10',
    'w-12',
    'h-6',
    'w-6',
    'h-4',
    'w-4',
    'h-3',
    'w-3',
    'w-full',
    'h-full',
    'min-h-screen',
    'min-h-[400px]',
    'z-10',
    'z-20',
    'z-50',
    'z-0',
    'top-0',
    'top-4',
    'top-1/2',
    'left-4',
    'right-4',
    'bottom-0',
    'left-0',
    'transform',
    '-translate-y-1/2',
    '-translate-y-1',
    'shadow-md',
    'shadow-lg',
    'shadow-sm',
    'border',
    'border-0',
    'border-input',
    'border-transparent',
    'transition-colors',
    'transition-all',
    'duration-300',
    'duration-200',
    'ease-out',
    'ease-in-out',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-ring',
    'focus:ring-offset-2',
    'ring-offset-background',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'bg-card',
    'text-card-foreground',
    'bg-background',
    'text-foreground',
    'bg-muted',
    'text-muted-foreground',
    'bg-primary',
    'text-primary-foreground',
    'bg-secondary',
    'text-secondary-foreground',
    'bg-accent',
    'text-accent-foreground',
    'bg-destructive',
    'text-destructive-foreground',
    'bg-popover',
    'text-popover-foreground',
    'bg-gradient-to-r',
    'from-primary',
    'to-purple-600',
    'bg-clip-text',
    'text-transparent',
    'text-primary',
    'text-foreground',
    'text-muted-foreground',
    'text-destructive',
    'text-destructive-foreground',
    'text-primary-foreground',
    'text-secondary-foreground',
    'text-accent-foreground',
    'text-popover-foreground',
    'text-card-foreground',
    'text-red-500',
    'fill-current',
    'cursor-pointer',
    'cursor-default',
    'flex-shrink-0',
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          50: '#fef3c7',
          100: '#fde68a',
          200: '#fcd34d',
          300: '#fbbf24',
          400: '#f59e0b',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        neutral: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.5)' },
          '50%': { boxShadow: '0 0 30px rgba(59, 130, 246, 0.8)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.4)',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}